version: 2.1

# Define orbs for easier configuration
orbs:
  go: circleci/go@3.0.1
  docker: circleci/docker@2.4.0

# Define reusable commands
commands:
  setup_go_environment:
    description: "Set up Go environment and dependencies"
    steps:
      - checkout
      - go/install:
          version: "1.24.5"
          cache-key: 'go-mod-{{ .Environment.CACHE_VERSION }}-{{ checksum "go.mod" }}'
      - run:
          name: Download dependencies
          command: make install

  setup_aws_and_docker:
    description: "Setup AWS CLI and Docker for ECR operations"
    steps:
      - run:
          name: Install AWS CLI
          command: |
            if ! command -v aws &> /dev/null; then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
            fi
      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region us-west-2  | docker login --username AWS --password-stdin 183605072238.dkr.ecr.us-west-2.amazonaws.com
      - run:
          name: Create ECR repository if it doesn't exist
          command: |
            aws ecr describe-repositories --region us-west-2 --repository-names llm-proxy || aws ecr create-repository --region us-west-2 --repository-name llm-proxy

# Define jobs
jobs:
  lint:
    docker:
      - image: cimg/base:stable
    working_directory: ~/llm-proxy
    steps:
      - setup_go_environment
      - run:
          name: Run go vet
          command: go vet ./...
      - run:
          name: Run go fmt check
          command: |
            if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
              echo "Go code is not formatted:"
              gofmt -s -l .
              exit 1
            fi

  test:
    docker:
      - image: cimg/base:stable
    working_directory: ~/llm-proxy
    steps:
      - setup_go_environment
      - run:
          name: Run unit tests
          command: make test

  build-and-push:
    docker:
      - image: cimg/base:stable
    working_directory: ~/llm-proxy
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - setup_aws_and_docker
      - run:
          name: Build and push Docker image
          command: |
            ./scripts/build_for_ecr.sh

# Define workflows
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - lint:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/

      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/

      - build-and-push:
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              ignore: /.*/
          context:
            - AWS
