# LLM Proxy Configuration
# This file configures rate limiting, cost tracking, and model-specific settings

# Production configuration

enabled: true

features:
  cost_tracking:
    enabled: true
    async: true
    workers: 8
    queue_size: 500
    flush_interval: 15
    transports:
      - type: "dynamodb"
        dynamodb:
          table_name: "llm-proxy-cost-tracking"
          region: "us-west-2"
      - type: "datadog"
        datadog:
          host: "localhost"
          port: "8125"
          namespace: "llm_proxy"
          tags: ["env:prod", "service:llm-proxy", "team:platform"]
          sample_rate: 1.0
      - type: "file"
        file:
          path: "./logs/cost-tracking-backup.jsonl"
  rate_limiting:
    enabled: false
