# LLM Proxy Configuration
# This file configures rate limiting, cost tracking, and model-specific settings

# Staging configuration

enabled: true

features:
  cost_tracking:
    enabled: true
    # Staging: Test both DynamoDB and Datadog transports
    transports:
      - type: "dynamodb"
        dynamodb:
          table_name: "llm-proxy-cost-tracking-staging"
          region: "us-west-2"
      - type: "datadog"
        datadog:
          host: "localhost"
          port: "8125"
          namespace: "llm_proxy"
          tags: ["env:staging", "service:llm-proxy"]
          sample_rate: 1.0
  rate_limiting:
    enabled: false
