# LLM Proxy Configuration
# This file configures rate limiting, cost tracking, and model-specific settings

# Staging configuration

enabled: true

features:
  cost_tracking:
    enabled: true
    # Staging: Test both DynamoDB and Datadog transports
    transports:
      - type: "dynamodb"
        dynamodb:
          table_name: "llm-proxy-cost-tracking"
          region: "us-west-2"
  rate_limiting:
    enabled: false
